"""
finmentor — Compliance Layer
==============================
Applies two mandatory post-processing passes to all LLM-generated advice:

  Pass 1 — Stock Scrubber
      Detects and removes/replaces specific stock or company recommendations.
      The agent should recommend *categories* (large-cap index fund) not
      *names* (Reliance Industries, HDFC Bank).  Any slip-through from the
      LLM is caught here as a safety net.

  Pass 2 — Disclaimer Injector
      Appends the mandatory SEBI-aligned disclaimer to every advice string
      before it reaches the user.

Design notes
------------
  • BANNED_PATTERNS is a compiled list of regex patterns (case-insensitive).
    The match group captured is added to violations_found for audit logging.
  • Replacement text is generic category language so the advice still reads
    naturally after scrubbing.
  • The disclaimer text is stored as a constant — update DISCLAIMER_TEXT
    when legal/compliance requirements change.
  • ComplianceResult carries both original_advice and scrubbed_advice so
    the audit trail is never lost.
"""

from __future__ import annotations

import re

from app.agents.shared.types import ComplianceResult

# ─────────────────────────────────────────────────────────────────────────────
# Disclaimer
# ─────────────────────────────────────────────────────────────────────────────

DISCLAIMER_TEXT: str = (
    "\n\n---\n"
    "**⚠️  Disclaimer:** This analysis is generated by an AI financial assistant "
    "and is intended for **informational and educational purposes only**. "
    "It does not constitute financial, investment, tax, or legal advice. "
    "Past performance of any instrument is not indicative of future results. "
    "Mutual fund investments are subject to market risks — please read all "
    "scheme-related documents carefully. "
    "Tax computations are based on FY 2024-25 rules and may not reflect the "
    "latest Budget amendments. "
    "Always consult a SEBI-registered investment adviser or a qualified "
    "Chartered Accountant before making financial decisions.\n"
    "---"
)

# ─────────────────────────────────────────────────────────────────────────────
# Banned stock / company patterns
# ─────────────────────────────────────────────────────────────────────────────
# Each entry: (pattern_string, replacement_text)
# Pattern is compiled with re.IGNORECASE.
# Keep patterns specific enough to avoid false positives on common words.

_RAW_PATTERNS: list[tuple[str, str]] = [
    # ── NSE/BSE listed large-caps commonly mentioned by LLMs ─────────────
    (r"\bReliance\s+Industries?\b",          "a large-cap energy conglomerate"),
    (r"\bHDFC\s+Bank\b",                     "a leading private-sector bank"),
    (r"\bICICI\s+Bank\b",                    "a leading private-sector bank"),
    (r"\bState\s+Bank\s+of\s+India\b",       "a public-sector bank"),
    (r"\bSBI\b(?!\s+(?:FD|Mutual|Life))",    "a public-sector bank"),   # SBI alone but not SBI FD / SBI Life
    (r"\bInfosys\b",                          "a large-cap IT company"),
    (r"\bTCS\b",                              "a large-cap IT company"),
    (r"\bTata\s+Consultancy\b",              "a large-cap IT company"),
    (r"\bWipro\b",                            "a mid/large-cap IT company"),
    (r"\bHCL\s+Tech\b",                      "a large-cap IT company"),
    (r"\bBajaj\s+Finance\b",                 "a leading NBFC"),
    (r"\bMaruti\s+Suzuki\b",                 "a large-cap auto company"),
    (r"\bAsian\s+Paints\b",                  "a large-cap consumer company"),
    (r"\bNestle\s+India\b",                  "a large-cap FMCG company"),
    (r"\bHindustan\s+Unilever\b",            "a large-cap FMCG company"),
    (r"\bL&T\b",                              "a large-cap infrastructure conglomerate"),
    (r"\bLarsen\s+(?:and|&)\s+Toubro\b",     "a large-cap infrastructure conglomerate"),
    (r"\bAdani\s+\w+",                        "an infrastructure/energy company"),
    (r"\bZomato\b",                           "a new-age internet company"),
    (r"\bSwiggy\b",                           "a new-age internet company"),
    (r"\bPaytm\b",                            "a new-age fintech company"),
    # ── NSE tickers ──────────────────────────────────────────────────────
    (r"\bNSE:\s*[A-Z]{2,10}\b",              "a listed equity"),
    (r"\bBSE:\s*\d{6}\b",                    "a listed equity"),
    # ── Crypto ───────────────────────────────────────────────────────────
    (r"\bBitcoin\b",                          "a high-risk cryptocurrency asset"),
    (r"\bEthereum\b",                         "a high-risk cryptocurrency asset"),
    (r"\b(?:crypto|cryptocurrency)\s+invest\w*\b",
                                              "cryptocurrency (which carries very high risk and is unregulated in India)"),
    # ── Specific mutual fund scheme names ────────────────────────────────
    (r"\bMirae\s+Asset\s+\w+\s+Fund\b",      "a top-rated equity mutual fund"),
    (r"\bAxis\s+\w+\s+Fund\b",               "an equity mutual fund"),
    (r"\bSBI\s+\w+\s+Fund\b",               "an SBI mutual fund scheme"),
    (r"\bHDFC\s+\w+\s+Fund\b",              "an HDFC mutual fund scheme"),
    (r"\bICICI\s+Pru\w*\s+\w+\s+Fund\b",    "an ICICI Prudential mutual fund scheme"),
    (r"\bQuant\s+\w+\s+Fund\b",              "an actively managed equity fund"),
]

# Compile once at import time
BANNED_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(pat, re.IGNORECASE), replacement)
    for pat, replacement in _RAW_PATTERNS
]


# ─────────────────────────────────────────────────────────────────────────────
# Core functions
# ─────────────────────────────────────────────────────────────────────────────

def scrub_stock_recommendations(advice: str) -> tuple[str, list[str]]:
    """
    Replace specific stock/fund names in *advice* with category descriptions.

    Parameters
    ----------
    advice : Raw advice string from the ExplainerAgent.

    Returns
    -------
    (scrubbed_advice, violations_found)
        scrubbed_advice  — advice with banned names replaced.
        violations_found — list of matched patterns (for audit / logging).
    """
    scrubbed    = advice
    violations: list[str] = []

    for pattern, replacement in BANNED_PATTERNS:
        matches = pattern.findall(scrubbed)
        if matches:
            violations.extend(matches)
            scrubbed = pattern.sub(replacement, scrubbed)

    return scrubbed, violations


def inject_disclaimer(advice: str) -> str:
    """
    Append the mandatory SEBI-aligned disclaimer to *advice*.
    Idempotent — will not double-append if the disclaimer is already present.
    """
    marker = "⚠️  Disclaimer:"
    if marker in advice:
        return advice
    return advice + DISCLAIMER_TEXT


def run_compliance(advice: str) -> ComplianceResult:
    """
    Run the full compliance pipeline over a generated advice string.

    Steps
    -----
    1. Scrub banned stock/fund/company names.
    2. Inject the mandatory disclaimer.

    Parameters
    ----------
    advice : Raw advice text from the ExplainerAgent.

    Returns
    -------
    ComplianceResult — carries both original and scrubbed versions for auditing.
    """
    scrubbed, violations = scrub_stock_recommendations(advice)
    final = inject_disclaimer(scrubbed)

    return ComplianceResult(
        original_advice=advice,
        scrubbed_advice=final,
        violations_found=violations,
        disclaimer_injected=True,
    )